bin/config_sample/config.ini, include/aoclient.h, include/server.h, src/aoclient.cpp, src/commands.cpp, src/server.cpp
In this pull request, I'll be explaining exactly what I do to merge in 0.5 commits. But first, we need to clear something up. Because every time I post a half commit video, I get the same comments over and over asking what it means, even though I always have a whole paragraph in the description explaining it, which even starts with 'If you're wondering what a half commit is, read this before commenting to ask'.
=> Add two roll command, fix minor formatting on prior commands

include/aoclient.h, src/aoclient.cpp, src/commands.cpp, src/main.cpp, src/packets.cpp
=> Fixes and improvements

src/aoclient.cpp, src/packets.cpp
arup has to be sent after "DONE" otherwise the client will not use it
=> Fix spectators not being properly sent ARUP information

include/area_data.h, src/aoclient.cpp, src/area_data.cpp, src/server.cpp
=> Fix characters not being correctly marked as taken

include/server.h, src/packets.cpp
+ Remove unused server.h header entry
=> Prevent empty OOC name

src/packets.cpp
=> Check the other client's pos against ours before pairing

include/aoclient.h, src/commands.cpp
Mango was disappointed when they learned I already did this several days ago and forgot about it.
=> Add lm-command

bin/config_sample/areas.ini, include/aoclient.h, include/area_data.h, src/area_data.cpp, src/commands.cpp, src/packets.cpp
=> Add allow_blankposting-command

include/aoclient.h, src/aoclient.cpp, src/packets.cpp
- Fix current char being removed from the char_taken list too early
- Fix incorrectly setting char_id when argument is invalid
=> Fix character select menu being bugged on Akashi

bin/config_sample/areas.ini, include/aoclient.h, include/area_data.h, include/db_manager.h, src/area_data.cpp, src/commands.cpp, src/db_manager.cpp, src/packets.cpp
- Adds getBanInfo() to db_manager, which queries bans by banid, hdid, or ipid
- Adds a judgelog to each area and the helper function updateJudgeLog() to update it.
=> Add /judgelog and /baninfo commands

include/advertiser.h, include/aoclient.h, include/area_data.h, include/config_manager.h, include/server.h, src/advertiser.cpp, src/aoclient.cpp, src/area_data.cpp, src/commands.cpp, src/config_manager.cpp, src/logger.cpp, src/main.cpp, src/packets.cpp, src/server.cpp
=> Add a new system for loading configuration files

include/config_manager.h, include/server.h, src/commands.cpp, src/config_manager.cpp, src/server.cpp
Fixes an issue with the generation of /8balls questions, and cleans up the code slightly.
This should not be merged until #66 has been merged.
=> Minor fix to /8ball

bin/config_sample/text/gimp.txt, include/aoclient.h, include/server.h, src/commands.cpp, src/config_manager.cpp, src/packets.cpp, src/server.cpp
=> Add /gimp, /disemvowel, /shake, and their reverse commands

akashi.pro, bin/config_sample/config.ini, include/aoclient.h, include/area_data.h, include/server.h, src/commands.cpp, src/packets.cpp, src/server.cpp, src/testimony_recorder.cpp
+ Some explanation in the docs
=> Add testimony playback

include/aoclient.h, src/testimony_recorder.cpp
- Fix cmdAddStatement not being in the command table
- Fix add statement not correctly setting added statements to green text
=> Fix cmdAddStatement

include/aoclient.h, src/aoclient.cpp, src/packets.cpp
@Cerapter Someday you will have to answer for your actions, and God may not be so merciful.
Implements case announcements, the last remaining piece of FantaProtocol to be implemented in akashi.
Gaze upon my labor and weep, for it is an unholy abomination rivaling Lovecraft's creations for its otherworldly horror and existential dread.
I have been awake for 24 hours.
=> Implement case announcements

include/aoclient.h, src/commands/area.cpp
- Adds "UNCM" permissions for uncming
- Resolves #76
=> Allow moderators to uncm other clients

include/aoclient.h, src/commands/music.cpp, src/packets.cpp
people really need to stop forgetting to do this lmao
=> add missing commands to the command table

src/packets.cpp
Fixes force_immediate, making it correctly change the client's emote modifier.
Resolves #108
=> Fix force_immediate

akashi.pro, bin/config_sample/config.ini, include/discord.h, include/logger.h, include/server.h, src/discord.cpp, src/logger.cpp, src/packets.cpp, src/server.cpp
Collaborative PR by MangosArentLiterature and Salanto, both of which are now suffering from severe depression after having dealt with Qt's Boomer implementation of the Internet.
=> Add Discord Webhook for Modcall + Optional Buffer Log Upload

include/advertiser.h, src/advertiser.cpp
- Server will now attempt to reconnect to the master server when connection to it is lost.
=> Add disconnect handling

include/aoclient.h, src/commands/moderation.cpp
Allows you to kick a client based on UID.
=> Add /kickuid

core/src/packets.cpp
=> Make iniswap detection case-insensitive

bin/config_sample/config.ini, core/core.pro, core/include/config_manager.h, core/include/http_advertiser.h, core/include/server.h, core/src/commands/moderation.cpp, core/src/config_manager.cpp, core/src/http_advertiser.cpp, core/src/server.cpp
Attempt to implements server advertiser as described in AttorneyOnline/AO2-Client#550.
The former attempt was too merge conflicted to salvage.
=> Implement HTTP server advertiser

bin/config_sample/config.ini
=> Update sample config

core/src/commands/area.cpp
=> Make /bg case insensitive

core/src/commands/area.cpp
=> uninvite users who are area-kicked

core/src/commands/roleplay.cpp
=> Send conflip to the area instead of the client

core/src/commands/area.cpp
=> disallow cms from being area kicked

bin/config_sample/config.ini, core/include/config_manager.h, core/include/discord.h, core/include/server.h, core/src/commands/moderation.cpp, core/src/config_manager.cpp, core/src/discord.cpp, core/src/server.cpp
and you can actually turn it off!
=> Implement ban webhook

core/src/commands/messaging.cpp
=> Send confirm message on success of /pm

core/src/commands/area.cpp
=> Notify target of invite and uninvite

core/include/db_manager.h, core/src/db_manager.cpp
I didn't find a Qt way of doing this quickly enough so I used access(). Hope that's OK.
=> Add a check for file writability to the DB to confuse users slightly less.

core/include/config_manager.h, core/src/config_manager.cpp, core/src/discord.cpp
=> Fix Modcall Embed Construction Order

core/src/commands/area.cpp
=> Allow spaces to be contained in background names

bin/config_sample/config.ini, core/include/area_data.h, core/include/data_types.h, core/include/logger/writer_full.h, core/src/logger/u_logger.cpp, core/src/logger/writer_full.cpp
=> Implement Area-Sorted Logging

core/src/area_data.cpp
=> Fix Jukebox incorrectly discarding songs

core/src/area_data.cpp
addJukeboxSong now works correctly
=> Fixed Sal's oopsie

bin/config_sample/discord.ini, core/include/config_manager.h, core/include/discord.h, core/src/config_manager.cpp, core/src/discord.cpp
Virgin default color vs. Chad customizable color.
=> Add optional color configuration

core/src/commands/messaging.cpp
Tsu3 has the same lack of response, but who cares if your command worked or not?
=> Add neccessary error and success message to cmdCharSelect

bin/config_sample/text/logtext.ini, core/include/config_manager.h, core/src/config_manager.cpp, core/src/logger/u_logger.cpp
This was easier than expected.
=> Make log entries formatting reloadable and configurable

core/include/logger/u_logger.h, core/include/server.h, core/src/commands/moderation.cpp, core/src/logger/u_logger.cpp, core/src/server.cpp
Fixes an oversight that prevents logging from working when the config folder has not been updated yet.
=> Fix non-functional logger with older config folders.

bin/config_sample/config.ini, core/include/config_manager.h, core/include/http_advertiser.h, core/include/server.h, core/src/aoclient.cpp, core/src/config_manager.cpp, core/src/http_advertiser.cpp, core/src/packets.cpp, core/src/server.cpp
+ Some design changes because they are better imo.
=> Fix incorrect playercount when advertising

core/include/aoclient.h, core/include/server.h, core/src/aoclient.cpp, core/src/server.cpp
=> Simplify code for user id assignment

core/src/server.cpp
=> Change regex interpretation

core/src/commands/area.cpp
This is honestly the better variant. ngl.
Fixes #235
=> Make /getareas work like its Tsu counterpart

core/include/area_data.h, core/src/area_data.cpp, core/src/commands/music.cpp, core/src/server.cpp
=> Send song when client joins the area.

core/include/aoclient.h
GAS GAS GAS, I'M GONNA STEP ON THE GAS!
=> Alias getarea, getareas and roll

core/src/db_manager.cpp
Corrects several oversights and weird design decisions to make the code more resilient and clearer to read.
Fixes #237
=> Fix user deletion

core/include/aoclient.h
I should probably read what's going on with the changes rather than merely glancing. Our friend /getarea got murdered. This spell should revive 'em.
=> Re-add /getarea

core/src/packets.cpp
=> Actually play music on areaJoin

core/src/area_data.cpp, core/src/packets.cpp
=> Fix #234 /  Exclude stop track from alias lookup.

core/src/packets.cpp
Resolves #256, this is tested so I'm fast-merging it.
=> Improve the modcall message to be more visible and include more information

core/src/packets.cpp
* Fixes incorrect lookup where the server would try to pair a user with another user outside the current users area.
=> Fix paired player check behaviour

core/include/aoclient.h
I shouldn't be allowed to write code sometimes.
=> Fix new connected client not being a spectator

core/src/acl_roles_handler.cpp
=> The fix to the fix. (ACL Roles)

core/include/aoclient.h, core/include/crypto_helper.h, core/include/db_manager.h, core/src/commands/authentication.cpp, core/src/db_manager.cpp, tests/tests.pro, tests/unittest_crypto/tst_unittest_crypto.cpp, tests/unittest_crypto/unittest_crypto.pro
=> Add more secure password hashing support

core/src/config_manager.cpp, core/src/server.cpp, tests/unittest_config_manager/tst_unittest_config_manager.cpp
* Someone should test this on linux.
=> Fix musiclist duplication

bin/config_sample/text/commandhelp.json
=> /setperms and /removeperms get documented again

core/src/server.cpp
Good enough for now, server needs to be reworked at some point anyway.
=> Workaround due to MSVC not running constructor in order

akashi.pro
This should improve compile times on multi-core CPUs since tests and core can compile at the same time.
=> Change ordered config to depends

core/core.pro
Resolves https://github.com/AttorneyOnline/akashi/issues/334.
Oh no who left this here
=> Change project default defines

core/include/packet/packet_ms.h, core/src/packet/packet_ms.cpp
Reverts AttorneyOnline/akashi#338
Causes a segfault, needs investigation
=> Revert "Check for doubleposts per client, not per area"

core/src/packet/packet_ms.cpp
for backgrounds with multiple wit positions
=> Allow testimony to be recorded from any "wit" position

core/include/area_data.h, core/src/aoclient.cpp, core/src/area_data.cpp, core/src/commands/music.cpp
=> Allow areas to set whether or not /play requires CM

core/src/network/network_socket.cpp
I don't know why this bit of code was causing it, but it was. ¯\\\_(ツ)\_/¯
=> Fix "stop music on object" blocking incoming IC message

core/src/packet/packet_id.cpp, core/src/packet/packet_ms.cpp
Necessary boilerplate for both https://github.com/AttorneyOnline/AO2-Client/pull/953 and https://github.com/AttorneyOnline/AO2-Client/pull/780.
=> Boilerplate for client pull request

bin/config_sample/ambience.ini, bin/config_sample/command_extensions.ini, bin/config_sample/text/commandhelp.json, core/include/aoclient.h, core/include/area_data.h, core/include/config_manager.h, core/src/aoclient.cpp, core/src/area_data.cpp, core/src/commands/area.cpp, core/src/commands/music.cpp, core/src/config_manager.cpp
Can be configured automatically per-background or set manually with the same permission structure as /play. Resolves #348
=> Add support for background ambience

core/src/testimony_recorder.cpp
off by one errors my beloathed
=> Fix adding testimony appending new statements BEFORE the current one

bin/config_sample/config.ini, bin_tests/config/config.ini, src/advertiser.cpp, src/advertiser.h, src/aoclient.h, src/config_manager.cpp, src/config_manager.h, src/main.cpp, src/network/network_socket.cpp, src/network/network_socket.h, src/packet/packet_id.cpp, src/server.cpp, src/server.h, tests/unittest_config_manager/tst_unittest_config_manager.cpp
Resolve AttorneyOnline/AO2-Client#987, resolve AttorneyOnline/AO2-Client#1007
=> Removed TCP server entry point

src/aoclient.cpp, src/commands/area.cpp, src/config_manager.cpp, src/config_manager.h
=> Add server tag support

bin/config_sample/discord.ini, src/config_manager.cpp, src/config_manager.h, src/discord.cpp, src/discord.h, src/packet/packet_ma.cpp, src/server.cpp
The feature was a novelty at best, but realistically it is useless and a mess.
=> [Deprecation] Remove uptime webhook

.gitignore
every time i build it i get like 10 of these
=> fuck moc files

.gitignore, bin/config_sample/config.ini, src/aoclient.cpp, src/aoclient.h, src/commands/area.cpp, src/config_manager.cpp, src/config_manager.h, src/serverpublisher.cpp
allows to send an ssl port to the ms in case you have nginx set up or something else
=> add ssl port

bin/config_sample/command_extensions.ini, bin/config_sample/text/autorp.json, bin/config_sample/text/commandhelp.json, core.pro, src/aoclient.cpp, src/aoclient.h, src/area_data.cpp, src/area_data.h, src/commands/area.cpp, src/commands/messaging.cpp, src/medieval_parser.cpp, src/medieval_parser.h, src/packet/packet_ms.cpp, src/server.cpp, src/server.h
Hark! This pull requesteth be to add "Medieval Mode," ye popular game mode from Team Fortress 2, to akashi. Guvnor!
=> [Ye Olde Feature] Medieval Mode

src/aoclient.cpp
Just because you look like them does not mean you are them >:(
=> Fix persistent invitations
