AttorneyOnline/akashi

- include/aoclient.h
- include/area_data.h
- include/server.h
- src/aoclient.cpp
- src/area_data.cpp
- src/commands.cpp
- src/logger.cpp
- src/packets.cpp
- src/server.cpp
User IDs are a clone of the existing functionality in tsuserver3. On connection, the client is given the first available ID.
The "current_cm" area parameter has been replaced with a QList of IDs called "owners". Commands that should be limited to CMs can check the client's ID against the list of owners.
> Add a numerical user ID system, add CM commands, add document commands, add area locking (and spectating)

- include/aoclient.h
- include/area_data.h
- include/server.h
- src/aoclient.cpp
- src/area_data.cpp
- src/commands.cpp
- src/packets.cpp
- src/server.cpp
Timer 0 is the server-wide timer, and requires the `GLOBAL_TIMER` permission to alter. Implementation is otherwise identical to https://github.com/Crystalwarrior/KFO-Server.
> Add support for 2.9 timers

- include/aoclient.h
- include/config_manager.h
- src/config_manager.cpp
- src/packets.cpp
De-zalgo functions identically to tsuserver3 (down to using the exact same regular expression) and is used for:
- IC message
- IC showname
- OOC message
- OOC name
> Add "dezalgo" for IC and OOC chat

- bin/config_sample/areas.ini
- src/area_data.cpp
- src/packets.cpp
If `iniswap_allowed` is configured `false` and an IC packet is received where the current character selected and the character folder parameter do not match, the IC packet will be rejected as invalid. Proper emote-level checking is still not implemented.
> Add rudimentary iniswap prevention

- include/aoclient.h
- src/commands.cpp
- src/packets.cpp
The AUTH packet is used like this:
**Server:** `AUTH#{state}#%`
`state`:
`1` or higher: Successful log-in. Displays the guard button.
`0`: Unsuccessful log-in attempt.
`-1` or lower: Log-out. Hides the guard button.
> Network authentication and support for expanded_desk_mods.

- src/packets.cpp
The AO Client supports up to twelve colors by default. We might want to actually support all of them.
> Fix-ICColor

- src/packets.cpp
> Fix shownames being set to a single space when the user does not specify one

- bin/config_sample/text/8ball.txt
- include/aoclient.h
- src/commands.cpp
Answers are shown publicly. Adds config/text/8ball.txt to add, remove, or change 8ball answers. Answers are picked randomly from this file.
Screenshot:
> Add /8ball and a text file to change its answers

- include/area_data.h
- src/area_data.cpp
- src/packets.cpp
- adds a last_ic_message string list to areas which stores the last IC message sent
> Add a blank space infront of additive messages, and prevent additive text between different characters

- include/aoclient.h
- src/packets.cpp
This changes the built-in anti spam to work like its counterpart in tsuserver3, which should help contribute to a near-identical experience.
> Use per-area antispam rather than per-client, allow for multiple subsequent blankposts

- bin/config_sample/areas.ini
- include/aoclient.h
- include/area_data.h
- src/area_data.cpp
- src/commands.cpp
- src/packets.cpp
Note that "immediate text processing" and "non-interrupting pres" are the same concept, but the former description is preferred.
> Add ability to force immediate text processing (/force_noint_pres) and command to toggle iniswapping (/allow_iniswap)

- include/aoclient.h
- include/server.h
- src/aoclient.cpp
- src/commands.cpp
- src/server.cpp
I didn't add /getafk because it's stupid and no one used it in tsuserver anyway.
Default timeout is 5 minutes, configurable via `afk_timeout` in config.ini. Time is in seconds.
Most people don't even know tsuserver *has* an AFK system, so akashi will notify you when you are considered AFK, and again when you are no longer AFK. You can force yourself to be considered AFK using /afk.
Also includes a fix for my last PR because I'm suffering from Dumb Bitch Disease and didn't notice it until I was neck deep in this one.
> Add an AFK system, and /afk

- src/main.cpp
stops an error from appearing in the server console when advertiser is turned off in config.ini
> Ensure the advertiser actually exists before connecting the reload signal/slot

- include/aoclient.h
- src/packets.cpp
- Fixes an issue with the testimony recorder checking for >[statement], where due to AO encoding, special characters would improperly match the regex. For example, "%[statement]" would become "\<percent>[statement]", thus matching against >[statement]. This commit decodes those characters first.
- Adds AOClient::decodeMessage() for decoding a QString.
> Decode MS packet before testimony recorder regex

- include/aoclient.h
- src/commands/area.cpp
- src/commands/messaging.cpp
cmdAfk is a command that changes the clients status to AFK. As such, it belongs under the messaging category, which includes commands that handle a clients self-management.
> Move cmdAfk to messaging category

- include/aoclient.h
- src/commands/messaging.cpp
Resolves an issue with /switch and /randomchar that caused them to not update a client's char_id, thus resulting in the client being unable to send IC messages. This correctly validates that changeCharacter() returned true, and then sets the char_id accordingly.
This also fixes an issue with /randomchar causing it silently fail if it picked a taken character.
Resolves #84
> Fix /switch and /randomchar

- include/aoclient.h
- include/area_data.h
- include/server.h
- src/area_data.cpp
- src/commands/command_helper.cpp
- src/commands/music.cpp
- src/commands/roleplay.cpp
- src/packets.cpp
- Refactors diceThrower(), cleaning up the code and improving the implementation. Cleans up the documentation and removes the obsolete enum RollType.
- Adds /togglemusic for toggling music playing in an area. CMed clients can still play music like normal.
- Adds toggle_music to areas and areas.ini, for setting the default value for music playing in an area. Defaults to true.
> Refactor AOClient::diceThrower() and add /togglemusic

- bin/config_sample/config.ini
- include/aoclient.h
- include/server.h
- src/aoclient.cpp
- src/area_data.cpp
- src/packets.cpp
- src/server.cpp
- Limits packets to under 16KB.
- Adds a configurable option to config.ini for setting the maximum amount of characters in an IC/OOC message.
- Limits the size of OOC names to 30 chars.
- The client already limits this, but this is an added precaution.
- Limits the length of shownames to 30 chars.
- Implements shownames_allowed for areas, for toggling whether shownames are allowed for messages in that area.
- Limits the amount of data the client can send to the server to 30KB over two sequential reads.
Resolves #98
> Add a size limit to packets and a configurable maximum character limit for messages.

- include/aoclient.h
- src/commands/area.cpp
- src/commands/messaging.cpp
- src/packets.cpp
For investigation segments and lobby scenes, the lead defense may want to enter first person mode to more accurately reflect the Ace Attorney games. In 2.9.1 onwards, an IC message with an empty emote will cause the viewport to not update, which creates the "first person" effect.
> Add first person mode

- include/config_manager.h
- include/server.h
- src/config_manager.cpp
- src/packets.cpp
- src/server.cpp
Replaces the dezalgo regex with a possibly more sensible one. Removes most of the unicode characters used by zalgo text without breaking languages. Works pretty well in testing. Removes zalgo_tolerance because it doesn't really work with this system and is unnecessary.
Also fixes the weird issues with question marks occasionally being stripped by dezalgo.
> Fix Dezalgo

- include/aoclient.h
- src/commands/authentication.cpp
- src/packets.cpp
This PR changes /login to no longer take command arguments. Instead, upon sending /login, you will enter an interactive "prompt", where your next OOC message will be interpreted as your login attempt (and will not be shown to other users). This prevents a typo from accidentally broadcasting your credentials to the entire area.
- Changes /login to take no command arguments, /login now sets a client state "is_logging_in".
- pktOocChat will now intercept a client's OOC message if they have this client state, and will interpret that as a moderator login.
- Adds the helper function loginAttempt() for handling moderator logins.
> Change /login to use a "prompt" based system

- bin/config_sample/config.ini
- include/server.h
- src/packets.cpp
- src/server.cpp
- Adds a timer to run between IC messages, preventing IC messages from being sent until it times out.
- The duration of this timer is configurable.
> Set a floodguard between IC messages

- akashi/main.cpp
- bin/config_sample/config.ini
- core/core.pro
- core/include/area_data.h
- core/include/config_manager.h
- core/include/data_types.h
- core/include/logger.h
- core/include/server.h
- core/src/aoclient.cpp
- core/src/area_data.cpp
- core/src/commands/area.cpp
- core/src/commands/authentication.cpp
- core/src/commands/casing.cpp
- core/src/commands/command_helper.cpp
- core/src/commands/moderation.cpp
- core/src/commands/roleplay.cpp
- core/src/config_manager.cpp
- core/src/discord.cpp
- core/src/logger.cpp
- core/src/packets.cpp
- core/src/server.cpp
- core/src/testimony_recorder.cpp
Rewrites ConfigManager, which now loads and manages all config.ini values in addition to verifying server config files and directories. In addition, also adds a new DataTypes class for custom data types, as well as template function for converting between data types and QStrings.
Adds AuthType and LogType for server auth and logging values respectively. Changes every reference to these two config values to use the new types instead of QStrings, allowing for the use of switch statements, ensuring correct auth/logging types are used, and providing greater flexibility and readability. (For example, additional auth and logging modes can be added very easily).
Finally, this removes all config.ini loading from elsewhere in the code. ConfigManager is now the sole class for handling config.ini.
> Rewrite ConfigManager and introduce new types for auth and logging.

- core/include/aoclient.h
- core/src/commands/moderation.cpp
Sets /ban to require 3 arguments instead of 2
> Fix crash with /ban

- .gitignore
- core/include/area_data.h
- core/include/logger.h
- core/src/area_data.cpp
- core/src/logger.cpp
- core/src/packets.cpp
Logs commands separately from OOC messages, sending OOC messages straight to the OOC message logger, and only sending commands to the command logger. Previously, all OOC messages were treating as commands for logging purposes, which would cause issues when the command logger attempted to split apart the OOC message as if it were a command, particularly with blank messages, which would crash the server.
Also updates the .gitignore which nobody has touched in a good 10 years.
Fixes #139
> Log commands and OOC messages separately

- core/include/aoclient.h
- core/include/area_data.h
- core/src/area_data.cpp
- core/src/commands/area.cpp
- Adds the "ignore_bglist" option to areas, which toggles whether the BG list is enforced or ignored in an area.
- Adds a moderator permission "IGNORE_BGLIST" to give moderators the permission to toggle this setting.
- Adds a moderator command `/ignorebglist` to toggle this for an area.
Closes #136
> Add the ability to ignore the BG list per area

- bin/config_sample/config.ini
- core/include/discord.h
- core/include/server.h
- core/src/discord.cpp
- core/src/packets.cpp
- core/src/server.cpp
Completely refactors the Discord class, breaking it up into separate functions and slots, removing circular dependencies, and replacing most pointers with const references.
This also prepares the Discord class for additional webhook requests, instead of exclusively modcalls.
> Discord webhook refactor

- core/include/area_data.h
- core/include/db_manager.h
- core/src/area_data.cpp
- core/src/commands/moderation.cpp
- core/src/db_manager.cpp
- core/src/packets.cpp
- core/src/server.cpp
Allows you to ban any IPID, regardless of whether it is connected to the server or not. To accomplish this, IPIDs are used for IP bans instead of remote IPs.
In addition, this PR cleans up both isIPBanned() and isHDIDBanned() by removing extraneous DB queries. It removes getBanDuration and getBanReason, and instead isIPBanned and isHDIDBanned() will retrieve this info in it's single query.
Closes #96
> Allow banning clients not connected to the server

- core/include/aoclient.h
- core/src/testimony_recorder.cpp
And also add a space to some lines because they were 3 spaces for some reason.
> Prevent testimony messages containing "<" and ">".

- core/include/area_data.h
- core/src/aoclient.cpp
- core/src/area_data.cpp
- core/src/config_manager.cpp
- Load auth and log values in uppercase.
- Move evidencemod to an enum class.
- Fix LE packet being incorrectly encoded.
Fixes #146
> Fix evidence and config issues

- core/include/aoclient.h
Makes /mods useable only by users with MODCHAT permissions, effectively making it mod-only. This is to prevent users from easily knowing when moderators are online, thus stopping them from evading moderation.
> Make /mods only useable by moderators

- core/include/http_advertiser.h
- core/include/server.h
- core/src/commands/moderation.cpp
- core/src/http_advertiser.cpp
- core/src/server.cpp
Corrects oversight that causes ports to be reloaded in case they change in the config. Since Akashi cannot change its port mid-operation, that information needs to be excluded during a reload.
> Properly reload modern advertiser config

- core/include/area_data.h
- core/src/area_data.cpp
- core/src/commands/area.cpp
Currently, Akashi does not save the changed background in the area, meaning clients will default to the background of the config.
This commit addresses the issue by saving the new background in the area data, meaning it is persistent between people moving in and out of the area.
This PR addresses #178
> Set background in area data when /bg is used.

- core/include/aoclient.h
- core/src/commands/command_helper.cpp
- core/src/commands/moderation.cpp
/notice, when used, will send every user in the same area a packet that will cause a message box like this one to appear:
After two seconds, the user is allowed to press "OK" and continue use of the application. This is useful for when there is too much chaos for a moderator's voice to be heard, or for when you want to epicly troll people I guess.
> Add /notice, for moderators to be heard above the noise

- bin/config_sample/config.ini
It's loaded from the config, so it should probably be added here.
> Add missing afk timeout configuration to sample config

- bin/config_sample/config.ini
- core/include/config_manager.h
- core/src/config_manager.cpp
- core/src/discord.cpp
Allows ban webhooks to be send to another channel. Useful for public shaming
> Add ban webhook url option

- bin/config_sample/config.ini
- bin/config_sample/discord.ini
- core/include/config_manager.h
- core/include/discord.h
- core/include/server.h
- core/src/commands/moderation.cpp
- core/src/config_manager.cpp
- core/src/discord.cpp
- core/src/packets.cpp
- core/src/server.cpp
The Discord Webhook, while convenient, requires a reboot to update some settings of its operation, making it less than ideal for continuous operating in its current state.
This PR resolves these issues by redesigning some aspects of the Webhook to be easier to manage and less reliant on object persistence to keep track of aspects, like the uptime.
TODO :
Configuration file
Server
ConfigManager
Discord
> Refactor Discord class to be reloadable

- core/include/aoclient.h
- core/src/aoclient.cpp
this is done by waiting a maximum of one second to be certain a connection is established before beginning to read data from the socket
this needs testing by someone other than me
> Fix QIODevice::read (QTcpSocket) device not open error

- core/include/discord.h
- core/include/logger.h
- core/src/aoclient.cpp
- core/src/commands/area.cpp
- core/src/commands/authentication.cpp
- core/src/commands/casing.cpp
- core/src/commands/command_helper.cpp
- core/src/commands/messaging.cpp
- core/src/commands/moderation.cpp
- core/src/commands/music.cpp
- core/src/commands/roleplay.cpp
- core/src/config_manager.cpp
- core/src/db_manager.cpp
- core/src/discord.cpp
- core/src/packets.cpp
- core/src/server.cpp
- core/src/ws_client.cpp
- core/src/ws_proxy.cpp
- Used macro `Q_UNUSED()` to suppress "unused argument" warnings
- Corrected the order of `Logger`'s constructor arguments to fix "will be initialized before" warnings
- Liberal use of `const` and `qAsConst()` in range-for loops to fix "missing reference in range-for with non trivial type" and "c++11 range loop might detach Qt container" warnings
- Explicitly called `exec()` on the database creation queries initialized alongside `DBManager` to fix "unused QSqlQuery" warnings
- Added version-conditional refactors to code utilizing `QList::toSet()` which was deprecated in Qt 5.14 to fix "toSet() is deprecated" warnings
> Fix or suppress compiler warnings

- core/src/packets.cpp
> Remove QString::Splitbehaviour Deprication warning

- bin/config_sample/text/commandhelp.json
- core/include/aoclient.h
- core/include/config_manager.h
- core/src/aoclient.cpp
- core/src/commands/moderation.cpp
- core/src/config_manager.cpp
- core/src/server.cpp
Current, you are on your own when you want to know why your command fails. 
This PR adds a help information loader that allows users to get help texts right in the client + expands the general "Syntax error" messages into something helpful by providing you the correct syntax.
closes #59
> Implement help information handling

- core/src/db_manager.cpp
It was apparently perfectly acceptable to some that it shows an error when the file did not even have a chance to exist.
> Fix database permission error when database is first created

- bin/config_sample/config.ini
Add Vanilla content host to the sample config so Akashi stops crying about it each time a client even dares to connect.
> Stfu, asset url is valid now

- core/include/aoclient.h
- core/include/server.h
- core/src/commands/messaging.cpp
- core/src/server.cpp
- core/src/testimony_recorder.cpp
This also has an example that makes moderation easier by sending mods an altered version of the global message to include a user IPID.
> Make it easier to reuse code targeting specific user groups

- bin/config_sample/text/commandhelp.json
- core/include/aoclient.h
- core/include/area_data.h
- core/src/aoclient.cpp
- core/src/area_data.cpp
- core/src/commands/area.cpp
This allows CMs to set a message that can be sent when a client joins the area.
Useful for behaviour rules of specific areas, RP Guidelines, general info to the case, etc. Unlike Doc you can toggle if it sends or not.
> Add Area Messages

- core/include/config_manager.h
- core/src/area_data.cpp
- core/src/config_manager.cpp
- core/src/packets.cpp
Allows you to alias songs by providing the main name as a "Friendly name", while the actual song name can be an URL or a different name.
Solves the ancient issue of "but MOM, it's called [Insert Japanese Weaboo name here" and allows servers without dedicated WebAO repository to have their music be streams.
> Add ability for the musiclist entires to be an alias of another song.

- core/include/area_data.h
- core/src/aoclient.cpp
- core/src/area_data.cpp
- core/src/packets.cpp
- core/src/server.cpp
- tests/unittest_area/tst_unittest_area.cpp
Adds the server-assigned clientid to the area, allowing the server to exclusively broadcast to this area without checking each clients area.
Tests have been adjusted to account that area leaving and joining can now be identified by userid.
> Change broadcast to area to use userIDs instead of iterating over all joined clients.

- core/include/server.h
- core/src/server.cpp
Adds a bias towards lower user ids.
This change is purely aesthetic to bring Akashi closer to Tsu3 from a user experience standpoint.
> Switch queue with stack

- core/src/packets.cpp
This packet allows servers to overwrite the server description, allowing them to display them even in the favourites menu.
> Add server description to the PN packet

- core/include/ws_client.h
- core/src/advertiser.cpp
- core/src/ws_client.cpp
This helps when the websockets are behind a proxyserver, like Cloudflare
> Detect Proxyserver when a websocket connects

- core/src/commands/moderation.cpp
- core/src/config_manager.cpp
> Correct loadCommandHelp variable names, return if too many arguments on help, and add behaviour if no help exists
Fixes the following odd behaviour snippets:
/help asdf
/help baninfo 19 dollar fortnite card
> Fix help displaying nothing if it can't find the command + loadCommandHelp variable name fixes

- core/src/packets.cpp
Fixes a crash that occurs when a client sends less than the expected amount of arguments in an MS#% packet (for the 2.6+ and 2.8+ portions), by verifying the client has actually sent the required amount before checking them.
> Properly validate MS#% args length

- core/src/ws_client.cpp
Prevents IP spoofing with modified headers and ensures the header is sent by the provider.
> Check if proxy connection is coming from an local tunnel

- core/src/commands/messaging.cpp
Slightly better variable names too while we're at it
In a longer explanation, the behaviour was flipped, and users saw IPIDs while mods saw nothing, rather than the other way around.
> Don't Display IPIDs to Users via Global Chat

- core/src/commands/authentication.cpp
Otherwise, the syntax is `/changepass <Password>` or `/changepass <Moderator> <Password>`, rather than `/changepass <Password> 'Moderator'`, like how it's specified to be
(I meant arg 0 in my own commit, but basically, the first argument should be the password)
> Ensure /changepass always has arg 0 as the password

- .github/workflows/main.yml
This prevents TLS issues due to the lack of OpenSSL in the user's path.
> Add OpenSSL to Windows CI

- core/include/aoclient.h
- core/include/server.h
- core/src/commands/moderation.cpp
- core/src/server.cpp
closes #275 
Adds an hwid lookup to the kick_other to account for potential IP issues due to IPv6/IPv4 protocol shenanigans.
This is not foolproof because a client can only kick_other other clients and same IPID, same with WebAO. 
About as good as we can make it.
> Expand kick_other to consider the hwid

- core/src/packets.cpp
closes #254 
**NOTE : THIS IS A HACK AND A PROPER SOLUTION WOULD REQUIRE A CLIENTSIDE CHANGE**
This bug happens due to WebAO not allowing the user to set their deskmod, causing the client to hide the jude desk as the "chat" option is used as a default. A proper fix would be to make WebAO able to utilise deskmod correctly or to disable the behaviour for all clients altogether.
> Overwrite "chat" deskmod option

- core/src/commands/area.cpp
- allow multiple arguments (discarding the rest and using the first)
- give the moderator feedback that they successfully unCMed someone rather than only telling the target
- tell those without permission they lack it rather than saying the command is invalid, as that implied /uncm didn't exist
nothing really major, just a minor touch-up
> Improve feedback and behaviour from /uncm

- core/src/commands/roleplay.cpp
Barely any change here, but it goes from
to
> Remove excessive spacing with /notecardreveal

- core/include/aoclient.h
- core/src/commands/command_helper.cpp
- core/src/commands/roleplay.cpp
Resolves #285 
I thought it was best to separate all the argument parsing into cmdRoll and all the dice rolling/server message stuff into diceThrower, but that ended up forcing me to make cmdRollP basically a large clone function of cmdRoll. Not the most elegant.
> Added dice notation to help command

- bin/config_sample/text/commandhelp.json
- bin_tests/config/text/commandhelp.json
- core/src/config_manager.cpp
> WIP: Help command aliases

- core/src/area_data.cpp
this just looks weird and omnious. now, it'll be the None instead
> Fix blank music stream

- core/src/packet/packet_cc.cpp
Prevents early-selection while the client is still in the handshake.
> Maybe fix characters becoming unselectable

- core/include/packet/packet_ms.h
- core/src/packet/packet_ms.cpp
Doing it per area neutered a lot of jokes, and was kind of awkward. Per client feels a lot more natural, and still serves to prevent spam about as well.
> Check for doubleposts per client, not per area

- akashi/main.cpp
- core/src/area_data.cpp
- core/src/packet/packet_mc.cpp
- core/src/server.cpp
Floodguard timers were running repeatedly, causing CPU usage to spike in the main event loop.
Fixes #315
> Fix CPU core maxing out, esp. on Linux and bump version for hotfix

- core/src/commands/music.cpp
regardless of what the area thinks. a SUPER user not being able to play a song is a bit odd
solution is quick and dirty (I literally just copied code from elsewhere). there's likely a better way to do this
> Allow those with the CM perm to play music

- core.pro
- src/acl_roles_handler.cpp
- src/akashidefs.cpp
- src/akashidefs.h
- src/aoclient.h
- src/area_data.cpp
- src/command_extension.cpp
- src/commands/casing.cpp
- src/commands/command_helper.cpp
- src/config_manager.cpp
- src/data_types.h
- src/packet/packet_casea.cpp
- src/packet/packet_ct.cpp
- src/packet/packet_hi.cpp
- src/packet/packet_id.cpp
- src/packet/packet_ms.cpp
- src/packet/packet_rt.cpp
- src/packets.cpp
- src/server.cpp
- tests/unittest_aopacket/tst_unittest_aopacket.cpp
Resolve #360, resolve #361
* Dropped Qt5
* Now targets Qt6.5
* Dropped backward compatibility/feature list
> Dropped Qt5, drop backward compatibility/feature list

- README.md
- src/packet/packet_ms.cpp
One instance of QRegExp made the compiler crash when trying to build Akashi with Qt6. Also, the README.md build instructions were outdated, new ones were provided to me by Salanto.
> QRegExp to QRegularExpression and updated README

- README.md
Path changed in https://github.com/AttorneyOnline/akashi/commit/040f5a32161ba241832d15d514316739ebf67986#diff-ae8d834c42c9d4ecb756f7c94dfb45466562c5b20ced9f64c6fdf313f0b28aa2, updating here.
> Fix icon path in README.md

- core.pro
- src/aoclient.cpp
- src/commands/command_helper.cpp
- src/commands/messaging.cpp
This is done by setting internal player name to include "[AFK]" so that it appears in the player list. When the player next chats, the server will notice their name no longer contains "[AFK]" and automatically update it again.
Also removed the marker from /getarea since this would make it redundant.
> Mark AFK players in the player list

- src/packet/packet_ms.cpp
Closes #392
- Don't set the client's position for no reason
- Don't stop positions other than wit from recording testimony
> Fix issues related to testimony recording and the "wit" position

- bin/config_sample/command_extensions.ini
- src/commands/casing.cpp
end is most commonly used, provides more clarity that the testimony has "stopped" and further testimony is via /add and /update.
> Add hints in testimony, add pause alias.

- src/packet/packet_ms.cpp
Allows for clean recording of paired testimony when one character simply updates animation for every statement (i.e. mood matrix)
Also prevents accidental blankposts from being recorded in the annals of history
> Do not record blank posts as testimony

- Dockerfile
- docker-compose.yml
- docker-entrypoint.sh
This PR adds a `Dockerfile` and a `docker-compose.yml` for building akashi as a Docker image and running it with [Docker Compose](https://docs.docker.com/compose/).
`docker compose up -d`
This will build the image using the Dockerfile, then create a container on port `27016` with a bind mount at `./config`. The config folder will be created automatically if it doesn't exist. If the folder is empty, then the example config files from `config_sample` (generated by the build) will be copied into it on startup. This should allow it to work out of the box on the first startup, then the user can edit the config files and run `docker compose restart` for the changes to take effect.
The Dockerfile uses a [multi-stage build](https://docs.docker.com/build/building/multi-stage/) to try and keep the …
> Add Docker support

- src/discord.cpp
Before :
After : 
I consider the more compact approach a lot less jarring and reflects how the actual logfile on system storage looks like.
> [FIX] Remove extra linebreak from discord log upload
